/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {
   

    public static void main(String[] args) {
        
        Connection conn = ConnectionFactory.getConnection();
        
        ConnectionFactory.closeConnection(conn);
        
        
//        ProjectController pc = new ProjectController();
//       
//        Project p = new Project();
//        p.setName("Zeca");
//        p.setDescription("Teste");
//        pc.save(p);
        
//        p.setId(1);
//        p.setName("Zabo");
//        p.setDescription("Teste");
//        pc.update(p);
        
        
//        List<Project> list = pc.findAll();    
//        System.out.println("Projetos " + list.size());
//
//         pc.removeById(1);
//        
//        TaskController tc = new TaskController();
//        
//        Task t = new Task();
//        t.setIdProject(2);
//        t.setName("Criar tela");
//        t.setDescription("test");
//        t.setNotes("nada");
//        t.setCompleted(false);
//        t.setDeadline(new Date());
//        
//        tc.save(t);
//        
//        
//        t.setName("Alterar tela");
//        tc.update(t);
//        
//        List<Task> tasks =  tc.findAll(2);
//        System.out.println("tarefas " + tasks.size());
   }
}
